export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const ADD_STUDENT_LOADING = "ADD_STUDENT_LOADING";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";

export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";
export const DELETE_STUDENT_LOADING = "DELETE_STUDENT_LOADING";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";

export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
export const EDIT_STUDENT_LOADING = "EDIT_STUDENT_LOADING";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";

export const FETCH_STUDENT_ERROR = "FETCH_STUDENT_ERROR";
export const FETCH_STUDENT_LOADING = "FETCH_STUDENT_LOADING";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";